export const LEXICO_Z = [
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z70w.htm", title: "Zona Foraminiferal Inferior (Formaci�n Col�n)", age: "Edad no especificada", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z71w.htm", title: "Zona Foraminiferal Superior (Formaci�n Col�n)", age: "Edad no especificada", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z1w.htm", title: "Zamuro, Miembro (Formaci�n Misoa)", age: "Edad no especificada", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z2w.htm", title: "Zapa, Formaci�n", age: "INVALIDO CRETACICO", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z20w.htm", title: "Zarate, Conglomerado", age: "Edad no especificada", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z3w.htm", title: "Zaraza, Capas de, Grupo, Serie", age: "INVALIDO TERCIARIO (Mioceno) Estado Guárico Stehlin (1928) empleó el término Serie Zaraza para designar areniscas fosilíferas cerca del pueblo del mismo nombre. Kamen-Kaye (1942) mencionó el Grupo Zaraza. Sellier de Civrieux (1956 Léxico Estratigráfico de Venezuela) reseñó los datos conocidos para la fecha. Su empleo posterior fue resumido por Salvador (1964-b) quien recomendó su rechazo. Las capas se incluyen en la Formación Chaguaramas de uso actual. Véase CHAGUARAMAS, Formación . Referencias Kamen-Kaye, M., 1942. "Ortiz Sandstone" and "Guarumen Sandstone Group" of northcentral Venezuela. Amer. Assoc. Petról. Geol. , Bull., 26(1): 126-133. Ministerio de Minas e Hidrocarburos, 1956. Léxico Estratigráfico de Venezuela. Bol. Geol. Pub. Esp., 1, 728 p. Salvador, A., 1964-b. Proposed simplification of the stratigraphic nomenclature in the Eastern Venezuelan Basin. Asoc. Venez. Geol., Min. y Petról., Bol. Inform., 7(6): 153-202. Stehlin, M. C., 1928. Ein Astrapotherium Fund aus Venezuela. Eclog. Geol. Helv. , 21(1): 227-232. Bibliografía de Léxicos Anteriores Evanoff, J., 1951. Geología de la región de Altagracia de Orituco. Bol. Geol. , Caracas, 1(3): 237-264. González de Juana, C., 1946. Estudios sobre aguas subterráneas en los llanos de Venezuela , Rev. de Fomento (Venezuela), 8(64): 9-59. Hedberg, H. D., 1937. Stratigraphy of the Rio Querecual section of northeastern Venezuela, Geol. Soc. Am. , Bull., 48(12): 1971-2024. Hedberg, E. D., 1950. Geology of the eastern Venezuela basin (Anzoátegui-Monanagas-Sucre-eastern Guárico portion), Geol. Soc. Am. , Bull., 61(11): 1173-1216. Kraglievich, L., 1925. Sobre el supuesto Astrapotherium christi Stehlin descubierto en Venezuela (Xenastrapotherium n. gen.) y sus relaciones con Astrapotherium magnum y Uruguaytherium beaulieu , Edit. Franco-Argentina (Argentina), 16 p. Liddle, R. A., 1946. The geology of Venezuela and Trinidad , 2nd. ed., Paleont. Res. Inst., Ithaca, New York, 890 p. Patterson, J. M. y J. G. Wilson, 1953. Oil fields of Mercedes region, Venezuela, Am. Assoc. Petról. Geol., Bull., 37(13): 2705-2733. Simpson, G. G., 1943. Una tortuga del Terciario de Venezuela, Rev. de Fomento (Venezuela), 5(51-52)", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z4w.htm", title: "Zazarida, Formaci�n", age: "VALIDO PLEISTOCENO", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z60w.htm", title: "Zenda, Conglomerado de, Conglomerado Calc�reo de, Fase Conglomer�tica de, Caliza de, Miembro (Formaci�n Las Brisas)", age: "INVALIDO MESOZOICO", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z5w.htm", title: "Zenda, Fase (Formaci�n Las Brisas)", age: "VALIDO MESOZOICO", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z6w.htm", title: "Zenda, Miembro", age: "INVALIDO MESOZOICO", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z7w.htm", title: "Zeta, Miembro (Formaci�n Quiriquire)", age: "Edad no especificada", description: `nan` },
  { url: "https://labgeomucv.ing.ucv.ve/dist/Lexico/z8w.htm", title: "Zuata, Formaci�n", age: "INVALIDO TERCIARIO (Mioceno) Estado Guárico Hedberg (1950-a, p. 1.204) introdujo este término (mal escrito "Suata"). Junto con las formaciones Cucharo y Santa Lucía, infrayacentes, Salvador (1964-b) recomendó rechazar la Formación Zuata por no existir criterios válidos para establecer su contacto basal, a pesar de que su contacto superior con la Formación Freites está bien definido. Referencias Hedberg, E. D., 1950-a. Geology of the eastern Venezuela basin (Anzoátegui-Monanagas-Sucre-eastern Guárico portion), Geol. Soc. Am. , Bull., 61(11): 1173-1216. Salvador, A., 1964-b. Proposed simplification of the sttatigraphic nomenclature in the Eastern Venezuelan Basin. Asoc. Venez. Geol., Min. y Petról. , Bol. Inform., 7(6)", description: `nan` },
];
